version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
    - .env
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: mdillon/postgis:10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes:
      - ./.data/dbpgdata:/var/lib/postgresql/data